### ISSUE TITLE
News Feed 관리 작업을 해주실 분이 필요합니다.

### ISSUE THREAD

**Issue by S-H-G** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#10]
![image](https://cloud.githubusercontent.com/assets/19402718/20864268/18f87c5c-ba2d-11e6-844a-4780ccad0776.png)

**Comment by sthaga** [comment]
제가 해보긴 할 텐데 잘 모르는 사항이 많아서 몇 분 정도 더 하는 게 좋을 듯 싶습니다.
더불어 관리해야 할 프로젝트가 어떤 게 있을까요?
지금은 wordpress 하나밖에 제가 watch하고 있지 않아서 추가적으로 필요한 사항이 있으면
남겨주세요
