### ISSUE TITLE
[발표PPT] 3번의 발표PPT에 대해서 온라인상에 공유하는 것에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by S-H-G** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#11]
제목과 동일하게 저희가 발표했던 PPT에 대해서 온라인상에 공유하는것에 대해 1차, 2차, 3차 발표자분들의 동의를 구합니다.
 
 용도는 'slideshare'와 같은 Site에 올려서 wiki에 링크를 달아놓거나 삽입입니다.

**Comment by sthaga** [comment]
저는 찬성~

**Comment by Kn-Slyr** [comment]
저도 찬성입니다~

**Comment by taerok** [comment]
좋아요

**Comment by S-H-G** [comment]
OSS 프로젝트 조사발표 도팀 발표자료입니다. 
발표자 김진현 진우현
https://www.slideshare.net/secret/BdM2JZmOeVgtwZ

OSS 라이센스 조사발표 GNU Affero GPL 3.0 도팀 
발표자 박태록 서재학
https://www.slideshare.net/secret/uLncs7T1jo2TFT

오픈소스소프트웨어개론 팀구성발표 도
발표자 - 고대영, 김완석
https://www.slideshare.net/secret/LBFAqTR8fnLrZz
