### ISSUE TITLE
News feed 관련 예시

### ISSUE THREAD

**Issue by sthaga** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#12]
유형 : 버그 리포트
내용: theme.php 의 복수형으로 표기된 부분 -> 단수형으로 표기
 'post_content' => _x( 'This is an example of a homepage section. Homepage sections can be any page other than the homepage itself, including the page that shows your latest blog posts.', 'Theme starter content' ),

->

'post_content' => _x( 'This is an example of a homepage section. Homepage section can be any page other than the homepage itself, including the page that shows your latest blog posts.', 'Theme starter content' ), 

원문 : https://core.trac.wordpress.org/ticket/39107

대충 최근에 올라온 것 중 예시용으로 간단한 내용만 해봤는데 이런 식으로 작성하면 괜찮을까요?
의견 남겨주세요

**Comment by S-H-G** [comment]
넵! 그 프로젝트의 활동이 어떤식으로 이루어지는지 보여주는 부분이니 좋은 것 같습니다.
생각에는 'post_content' => _x( 'This is an example of a homepage section. Homepage sections can be any page other than the homepage itself, including the page that shows your latest blog posts.', 'Theme starter content' 부분을 삭제해도 괜찮지 않을까 싶습니다.

**Comment by sthaga** [comment]
이걸 이슈 하나에다가 쓰는 게 좋을까요 아니면 위키에 항목 하나를 더 만드는 게 더 보기 좋을까요?

**Comment by sthaga** [comment]
12/06/16 
유형 : 버그 리포트
내용 : 기본 WP content directory에서 WP content folder를 옮긴 후
theme, plugin 설치나 media file 업로드시 FTP connection을 묻는 문제 발생

원문 : https://core.trac.wordpress.org/ticket/39095


12/06/16
유형 : 버그 리포트
내용 : input field의 Placeholder 텍스트가 완전히 다 보이지 않음

원문 : https://core.trac.wordpress.org/ticket/39096


12/06/16
유형 : 변경사항
내용 : 필터링을 통해 렌더링에서 제외된 아이템이 있는 네비 메뉴를 선택적 새로고침이 

실패할 때 전체가 무한히 새로고침되는 것을 방지함
(Prevent infinite full refresh from occurring when selective refresh falls back for 

a nav menu that has items excluded from rendering via filtering.)

원문 : https://core.trac.wordpress.org/changeset/39511


12/06/16
유형 : 버그 리포트(개선안 제시)
내용 : 미리보기의 child element의 클릭시 미리보기가 안되는 링크의 탐색이 중단되지 

않음
(Clicking on child elements of preview links fails to abort navigation to non-

previewable links)

원문 : https://core.trac.wordpress.org/ticket/39098


12/06/16
유형 : 버그 리포트(개선안 제시)
내용 : 동기화 이후까지 모든 설정에 대해 선택적 새로고침 유발을 지연

원문 : https://core.trac.wordpress.org/ticket/39099



12/06/16
유형 : 버그 리포트
내용 : 페이지가 저장되고 게시되지 않을 시 편집 바로가기가 실행되지 않음

원문 : https://core.trac.wordpress.org/ticket/39100


12/06/16
유형 : 개선사항
내용 : about page의 반응형 image와 CDN media URL 관련 수정

원문 : https://core.trac.wordpress.org/changeset/39515


12/06/16
유형 : 버그 리포트(개선안 제시)
내용 : WP List에서의 게시물의 계층 구조를 표시하는 dashes(—) 대신 새로운 filter 적

용 제시 

원문 : https://core.trac.wordpress.org/ticket/39106


12/06/16
유형 : 버그 리포트
내용 : "Edit Media"에서 image의 이름 제거 시 untitled 대신 임의의 이름 강제 적용

원문 : https://core.trac.wordpress.org/ticket/39108

**Comment by Kn-Slyr** [comment]
와우 멋져요...  있다가 밤에 긁어다 업데이트 하겠습니다....

**Comment by sthaga** [comment]
12/06/16
유형 : 버전 업데이트
내용 : 기본 테마 Twenty Seventeen 소개
       테마 시작 콘텐츠
       비디오 헤더
       유연해진 메뉴 만들기
       사용자정의 CSS
       PDF 썸네일 미리보기
       언어별 관리자 화면
       사용자 지정 미리보기에서 편집 바로가기
       변경사항의 실시간 미리보기 가능
       Hook, 새 기능, 동작의 추가

원문 : https://make.wordpress.org/core/2016/12/05/wordpress-4-7-field-guide/       https://ko.wordpress.org/2016/12/07/%EC%9B%8C%EB%93%9C%ED%94%84%EB%A0%88%EC%8A%A4-4-7-%EB%B3%B8vaughan/
