### ISSUE TITLE
좋은 테마 적용중에 있습니다.

### ISSUE THREAD

**Issue by S-H-G** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#13]
이왕이면 갖고싶어서 MagicBook Theme를 통해 제 부분 github page를 구성하고자 합니다.
https://themeforest.net/item/magicbook-a-3d-flip-book-wordpress-theme/8808169

파일 구매 후 확인해보니
GPL license를 가지고 있네요
적용한 플러그인들 license 한번 확인해봐야겠네요

**Comment by S-H-G** [comment]
업로드 작업 완료 : http://shg-oss.esy.es/

산 보람있네요

**Comment by sthaga** [comment]
오 확실히 예쁘네요

**Comment by Kn-Slyr** [comment]
오오... 예쁘네요 static output도 잘되는군요...

**Comment by S-H-G** [comment]
진척사항 알려드립니다. static-output관련해서 문제가 생겨서 새벽내내 계속 잡고있었습니다.
지금 발표자료와 함께 1page부터 계속 만들고 있으니 http://shg-oss.esy.es/를 통해 확인바랍니다.

그리고 혹시 부족하다고 여기는 점이나 필요한 점 있으면 알려주시길 바랍니다.
(1page) 완
