### ISSUE TITLE
진척사항 알려드립니다.

### ISSUE THREAD

**Issue by S-H-G** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#14]
진척사항 알려드립니다. static-output관련해서 문제가 생겨서 새벽내내 계속 잡고있었습니다.[wget, HTT로 해결]
지금 발표자료와 함께 1page부터 계속 만들고 있으니 http://shg-oss.esy.es/를 통해 확인바랍니다.

그리고 혹시 부족하다고 여기는 점이나 필요한 점 있으면 알려주시길 바랍니다.
(1page) 완
*요청 : 1page 커버로 쓸만한 사진 구합니다.

+실수로 이슈 closed눌렀는데 치사하게 다시 안돌려주는..

**Comment by S-H-G** [comment]
(2-3page) 개요 - 참여활동

(4-5page) Wordpress 1차 발표자료[PPT] / link Wiki
참여자 역할 소개
OSS 프로젝트 조사발표 도팀 발표자료입니다.
발표자 김진현 진우현
https://www.slideshare.net/secret/BdM2JZmOeVgtwZ

(6-7page) AGPL 2차 발표자료[PPT] / link Wiki
참여자 역할 소개

OSS 라이센스 조사발표 GNU Affero GPL 3.0 도팀
발표자 박태록 서재학
https://www.slideshare.net/secret/uLncs7T1jo2TFT

(8-9page)

WordPress 관련 단체 소개 및 News Feed 구성 및 활동 연계 제시(1)
오픈소스소프트웨어개론 팀구성발표 도 
발표자 - 고대영, 김완석
https://www.slideshare.net/secret/LBFAqTR8fnLrZz

4~9page는 좌측 slideshare 삽입/우측에 위키 요약 붙임예정
*3page에 단계별 쓸 말 추천받습니다.

**Comment by Kn-Slyr** [comment]
단계별 쓸 말이라는게 이해가 잘 안가네요.. 
프로젝트 활동한거를 단계로 나누고 그 단계당 쓸 말을 말씀하시는 건가요?

**Comment by S-H-G** [comment]
@Kn-Slyr 
 아.. 설명이 미흡했네요. 
 저희가
step1 WAMP 등 서버를 구성하고,
step2 wordpress를 설치하고,
step3 Theme를 다운받고, 
step4 static홈페이지로 변환
을 이야기한것이였습니다.
https://ko.wordpress.org/%EB%82%B4-%EC%BB%B4%ED%93%A8%ED%84%B0%EC%97%90-%EC%9B%8C%EB%93%9C%ED%94%84%EB%A0%88%EC%8A%A4-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0/
에 잘 나와있긴한데 2~3줄 요약을 해야하는지라
 일단 전체 구성부터 다 해야겠다 싶어서 패스하고 페이지 틀부터 짜고있습니다..
10-11page 구성완료

**Comment by S-H-G** [comment]
끝페이지까지 구조형식은 다 했고 내용 채우면되네요.
4~9page는 어짜피 wiki들어가니 조금만 편집해서 넣으면 될거같고.


* 2 ~ 3page 단계설명과
* 10 ~ 11page 단계예시설명서 (나중에 튜토리얼)
* 12 ~ 13page newsfeed등 관련 프로젝트들 안내
 가 난감하군요

![image](https://cloud.githubusercontent.com/assets/19402718/20953293/bddad162-bc75-11e6-971f-ba60881b58bd.png)
slide 위아래로 30px만 줄이면 깔끔하게 들어갈듯용...
이공경 팀프 다녀와서 밤새가지고 눈 잠깐 붙이고 내용채워넣어야........... :) 
으어어...

**Comment by meditate1105** [comment]
다른거 간단하게 도울것이 있으면 바로 알려주세요 ㅠㅠ 사실 어떻게 접근하는지 잘 모르겠어서 일단 wiki 계속 수정하고 다듬을게요!

**Comment by S-H-G** [comment]
꿀잠 잘자서, 여러분들의 많은 도움 ppt에 잘 채워놓고 마무리 짓겠습니닷:)

**Comment by S-H-G** [comment]
완료 (complete)
