### ISSUE TITLE
wordpress github commit 변경사항 news feed

### ISSUE THREAD

**Issue by sthaga** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#15]
github commit 기록

Dec 5, 2016

- Customize: Ensure a `custom_css` post insertion gets an initial post …
(custom css 관련)
https://github.com/WordPress/WordPress/commit/0a31089bf6f5cb8182d497ba8eaff6e3a79c7459

- Build/Test Tools: Correctly set up the current screen during list tab…
(wp 버전 관련)
https://github.com/WordPress/WordPress/commit/89ef3af6553e85aea93b4b24e62b5ce2d9186362

- Twenty Seventeen: Add specific font stack for Thai language
(Thai langauge 폰트 적용 테마 업데이트)
https://github.com/WordPress/WordPress/commit/04da99389da56af9d5ffdfac37702262d1bdc8f7

- Twenty Seventeen: Improve display of video header and header image in…
(Twenty Seventeen theme의 비디오 헤더  관련 추가
https://github.com/WordPress/WordPress/commit/94506367ac6153f0330e8220530def36b98d2967

- Users: Clarify the return value of `get_current_user_id()` for non-lo…
(non-logged-in user에 대해 return value 설정
https://github.com/WordPress/WordPress/commit/5ffc6a7fe0588192c57fb09db1b0e570770861c5

- REST API: Treat any falsy value as `false` in 'rest_allow_anonymous_c…
(rest_allow_anonymous_comments 체크에 대해 모든 false value를 받도록 설정)
https://github.com/WordPress/WordPress/commit/87eedbd2f7368a41f237fdf03c59962533a6b1af

- REST API: Merge similar date strings in the revisions and comments co…
(comments controller 수정)
https://github.com/WordPress/WordPress/commit/f3b71b49d0b876d90a6e150432c0818f719cfd2e

- Comments: Merge similar strings between comments.php and the REST API
(comment.php 수정)
https://github.com/WordPress/WordPress/commit/697f079a190f531785f425058596b44befccef7b

- Multisite: Replace `is_super_admin()` with `manage_network` for admin…
(admin-bar 허가 수정)
https://github.com/WordPress/WordPress/commit/e72d3d6b5df14a072229dea45563e0b7631cfdcf

- Docs: Add inline documentation for `image-edit.js`.
(imageEdit method에 JSDoc DocBlock 추가)
https://github.com/WordPress/WordPress/commit/113833953d9ed387f4943970b6f9f19b5c92904a

- Role/Capability: Don't assign the `delete_site` capability to anyone …
(capability 관련 수정)
https://github.com/WordPress/WordPress/commit/597627fb920246d02088e11beb57d398ca6f3621

- Twenty Seventeen: Fix CSS specificity problem with CSS feature query 
(object-fit의 CSS 관련 문제 fix )
https://github.com/WordPress/WordPress/commit/6f5111d4e70babf4311ac2e2e16421fcaa7fed1c

- Default Themes: Update version numbers and readme files for 4.7 release
(4.7 release의 version number, readme file 업데이트)
https://github.com/WordPress/WordPress/commit/f0b2b3f98f685da4995321a86b28be516716eea0

- Customize: Ensure `textarea` for Custom CSS displays as code (in LTR)…
(RTL -> LTR 수정)
https://github.com/WordPress/WordPress/commit/c9b8a5dbbba0b6eab579836db8f27653c69317a5

Dec 6, 2016

- Customize: Prevent posts/pages imported via starter content from bein…
(nav menu 관련 수정)
https://github.com/WordPress/WordPress/commit/97f4180916b5465bd87a26dd12113c5e3811f6e6

- Customize: Ensure `changeset_uuid` query param is removed from the `c…
(customize control 관련 수정)
https://github.com/WordPress/WordPress/commit/6a3de4d857ff1eb59fa227d717b7c53293829272

- Customize: Defer populating `post_name` for `auto-draft` posts in cus…
( - )
https://github.com/WordPress/WordPress/commit/3b379031066b00e5186ca10cf850ccf606ba398f

- Comments: Merge a similar string between comments.php, XML-RPC and th…
(error message 수정)
https://github.com/WordPress/WordPress/commit/a5dbd53a465d3c0f1625225e946e74e138d79ddd

- Customize: Prevent infinite full refresh from occurring when selectiv…
(필터링을 통해 렌더링에서 제외된 아이템이 있는 네비 메뉴를 선택적 새로고침이 실패할 때 
전체가 무한히 새로고침되는 것을 방지함)
https://github.com/WordPress/WordPress/commit/672b8a61cd94e738f2a4a7fcc5770d6be446a908

- About page: Imagery and beautification.
(about page 수정)
https://github.com/WordPress/WordPress/commit/f336d4c8eaaf51d5459268302dd4c89e2882ecfe

- About page: Resposive images and CDN media URLs.
(about page 수정)
https://github.com/WordPress/WordPress/commit/da48e4ba1e6ad376aa991760b198fc51dfcfbcee

- About page: Bump image versions because CDN caching.
(about page 수정)
https://github.com/WordPress/WordPress/commit/3dea25bcd99d193db5b9602c77c7597369b85621

**Comment by sthaga** [comment]
12월 6일에 4.7 version이 release 되면서 (날짜가 한국날짜 기준인지는 잘 모르겠네요)
이전에 봤을 때는 없던 github에서 commit 기록이 갑자기 생겼습니다.

일단 내용들 보면서 어떤 사항이 변했는지 간략하게 써봤고 봐도 모르겠는 건 그냥
ㅁㅁ 관련 수정이나 - 로만 작성했습니다.
어제 commit 올라온 내용까지만 대략 써 놓았고 자세한 변경 사항은 링크 보시면 될 것 같습니다

**Comment by S-H-G** [comment]
수고하셨습니다.
확인하였습니다.

**Comment by sthaga** [comment]
Dec 7, 2016

- Remove 4.7 cruft from `$_old_files`.
(불필요 항목 제거)
https://github.com/WordPress/WordPress/commit/9c023fc883ff28d9d657778b2f2ad81d665ba550

- About page: Update video and REST API reference URLs.
(About page URL 수정)
https://github.com/WordPress/WordPress/commit/ab3bca05c8103a8a73ae482d149d7821d44e4b30

- Accessibility: Remove inappropriate content from the Media Library sc…
(Media Library 제목 항목 중 부적절한 컨텐츠 제거)
https://github.com/WordPress/WordPress/commit/26ef4bd86d3e3902d2cc5004125f041d76b2489f

- Accessibility: Remove inappropriate content from the Add Themes scree…
(Add Theme 제목 항목 중 부적절한 컨텐츠 제거)
https://github.com/WordPress/WordPress/commit/c1f59f9fe33ca38e918d4a03e53891494ca9bd7e

- Accessibility: Remove inappropriate content from the Themes screen he…
(Theme 화면 제목 중 부적절한 컨텐츠 제거)
https://github.com/WordPress/WordPress/commit/a9600d1a53d071fb4ef7e1904a5f1088392e7e8d

- Accessibility: Improve keyboard accessibility avoiding confusing tab …
(Media view에서 복잡한 tab 중지를 피하기 위한 키보드 접근성 개선)
https://github.com/WordPress/WordPress/commit/23ac0d061655c01055fba56f3c4c37b097a7f856

- Taxonomy: Correct the type for the first parameter of the `the_catego…
(category list의 type 변경)
https://github.com/WordPress/WordPress/commit/042d09001a61cc4850ea547a53deacf0a1dae57d

- Users: Style the super admin message on the user editing screen as a …
(편집 화면에서 최고 관리자 message 스타일 변경)
https://github.com/WordPress/WordPress/commit/16371b99d8e5111dcc83b8961b4d68681e82d25e


github commit 사항은 5일치부터 다 올린 것 같네요
