### ISSUE TITLE
튜토리얼 작성 관련

### ISSUE THREAD

**Issue by Kn-Slyr** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#19]
https://github.com/SKKU-OSS-DO/SKKU-OSS-DO.github.io/wiki/WordPress-for-Githubpage-Tutorial
일단 초안으로 슥슥 써봤는데 저번에 말한 것처럼 2번(워드프레스 튜토리얼)을 어느정도 채워줘야 할 지 모르겠네요..
4번도 내용상 GitHub에 파일 업로드 방법에 관한 내용이라 이것도 어느정도 써야할지 잘 모르겠어요...

**Comment by S-H-G** [comment]
@Kn-Slyr 
튜토리얼 작성 감사합니다. 
이번에 해당 발표page만들면서, 해당부분 스크린샷 찍으면서 진행하였습니다.
Github 파일 업로드 / Plugin관련 trouble 및 trouble shooting 관련하여 정리/작성하겠습니다.

12/17일날 작성 후, 그룹대화방에 1차적으로 알리겠습니다.
