### ISSUE TITLE
wiki 문법 영어 설명 번역

### ISSUE THREAD

**Issue by taerok** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#2]
검색하면 나오지만 핵심만 간단히 올려요.

## 번역 내용
1. 헤더는 # 개수에 따라 레벨이 결정되고 1, 2는 밑에 얇은 밑줄이 생기고 3부터는 없습니다.
2. 인용구는 >를 하고 뒤에 쓰면 회색 투명한 글자로 써집니다.
3. 리스트는 '*', '-'와 같이 앞에 부호만 붙이는거와 '1.', '2.'와 같이 인덱싱 2가지가 가능합니다.
4. 리스트의 경우 하위 리스트를 추가하고 싶으면 띄어쓰기 2번 후에 리스트를 만들면 됩니다.
5. 띄어쓰기 4번하면 코드 블럭이 만들어집니다. 이때 내용은 텍스트로만 출력됩니다.
6. 가로줄을 만들고 싶으면 --- 해주시면 됩니다.

##### 목차
    [Headers](#headers)  
    [Emphasis](#emphasis)  
    ...생략...    
    <a name="headers"/>
    ## Headers
위의 내용이 아래와 같이 나옵니다.
##### 목차
[Headers](#headers)  
[Emphasis](#emphasis)  
...생략...    
<a name="headers"/>
## Headers
---
위와 같이 하시면 됩니다.

**Comment by sthaga** [comment]
감사합니다~

**Comment by sthaga** [comment]
http://blog.kalkin7.com/2014/02/05/wordpress-markdown-quick-reference-for-koreans/

여기 참고하셔도 좋을 것 같습니다

**Comment by wskim3173** [comment]
유익한 내용 감사합니다.
