### ISSUE TITLE
Wordpress 위키 작성

### ISSUE THREAD

**Issue by sthaga** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#4]
목차는 다음과 같이 일단 만들었습니다

개요
역사
구조
장점
단점

진우현씨랑 발표했을 때처럼 나눠서 작성하면 될 듯 합니다
혹시 다른 분들 중에 의견 있으시면 달아주세요

**Comment by taerok** [comment]
우리가 github 페이지에 wordpress를 이용하는 것을 하는데 그것에 대한 내용도 간략하게 포함되면 좋을것 같습니다. 튜토리얼에서도 언급될꺼 같지만 우리가 기여하는 부분이니 중복되더라도 소개 한번 더 하는게 좋을 꺼 같아요. 튜토리얼에서 내용 완성하면 적당히 더 요약하거나 복사 붙여넣기로 넣으면 될꺼 같습니다.

**Comment by sthaga** [comment]
네 그럼 그 부분은 차후 튜토리얼 완성되면 추가하도록 하죠
다른 분들도 한 번 이슈 보시면 보셨다고 코멘트 남겨주시면 감사감사

**Comment by wskim3173** [comment]
이슈 확인 했습니다.
