### ISSUE TITLE
static page 작성 파트

### ISSUE THREAD

**Issue by Kn-Slyr** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#5]
### static page 작성 계획
1. WAMP와 WordPress 설치
2. WordPress 테마 선택 및 사용
3. 간단한 테스트를 위한 내용들 작성 
4.  static output plugin 중에 하나 선택해서 사용
5. plugin의 output을 repo에 commit

**Comment by Kn-Slyr** [comment]
현재는 1번 까지만 진행했습니다~

**Comment by S-H-G** [comment]
일이 하도 안풀려서 잠이 안오는 밤이네요.

4. Static output plugin에서
지난번 소개드렸던 https://wordpress.org/plugins/static-html-output-plugin/
보다는 https://wordpress.org/plugins/simply-static/ 작동률이 더 우수하네요.
4번 테스트 중에있습니다.

**Comment by S-H-G** [comment]
4번 정상작동 확인완료
Flippingbook플러그인을 적용한 페이지에서
Simply-static 플러그인 정상작동되네요

http://shg-oss.esy.es/

**Comment by S-H-G** [comment]
https://help.github.com/articles/creating-project-pages-using-the-command-line/
-수동 pages 작성법입니다.

**Comment by Kn-Slyr** [comment]
테마 적당한거 설치하고 4번 진행하려고 말씀하신 simply-static 써봤는데 이게 잘 작동은 하는데 제가 만든 wordpress페이지를 static output으로 만들어 주지 않고 php설치 초기페이지를 만들어주네요.
어디서 문제일까요?

**Comment by Kn-Slyr** [comment]
위에 문제는 해결했습니다.
설치할 때 좀 꼬여서 index.php파일 문제여서 결국 삭제하고 재설치 해서 해결했습니다.
말씀해주신 static output plugin 써서 만들어 봤는데 첫 페이지만 만들어지고 나머지 페이지들은 제대로 안 만들어지는것 같습니다. 
일단 static output만든거 commit해서 https://skku-oss-do.github.io/ 여기 들어가 보시면 확인 할 수 있습니다.

**Comment by S-H-G** [comment]
![image](https://cloud.githubusercontent.com/assets/19402718/20864251/6b332428-ba2c-11e6-9b34-d86c9ef15858.png)
![image](https://cloud.githubusercontent.com/assets/19402718/20864255/8c5a3e52-ba2c-11e6-8ad0-07f2ef8f89f1.png)

-static output log

**Comment by Kn-Slyr** [comment]
오오오오오 
프로젝트 처음 계획했을 때 찾았던 플러그인(https://wordpress.org/plugins/static-html-output-plugin/)인 이걸로 하니까 DB까지 탐색하는건지 모든 것(페이지, 포스트)을 static output으로 만들어 주네요
이거 한번 써보시는건 어떤가요?

**Comment by Kn-Slyr** [comment]
사용할 때 Settings - permalink Settings에서 저는 Plain으로 쓰고 있었는데 이러면 안된다고 바꾸라고 해서 Numeric으로 바꾸고 플러그인 사용할 때 Base Url에 이 static페이지를 올릴 주소를 적으면 되네요. 
예를들어 이번의 경우에는 루트가 되는 주소가 https://skku-oss-do.github.io/KDY/ 이니까 이대로 적으면 되고 로컬에서 테스트할 때는 이 파일들을 올려놓을 파일 위치를 적으면 되는 것 같아요.
클릭했을 때 링크거는 것 때문에 있는 기능인가 본데 상대주소로 안되고 절대주소로 되는게 좀 아쉽네요...

**Comment by S-H-G** [comment]
오오오오... 제 플러그인 에러 뿜길래, 새로운거 찾았는데 기능자체는 확실히 실사용도 좋고, 대단하네요

Simply-static / static-html-output-plugin 관련내용도 추가하겠습니다.

**Comment by Kn-Slyr** [comment]
현재까지 wiki에 작성되어 있는 내용들 업데이트 했습니다.

**Comment by S-H-G** [comment]
동적홈페이지를 만들때
Simply-static은 파일은 만들어주나 동적 홈페이지는 안만들어지고
Static-html-output-plugin은 index.html가 빈파일로 만들어지네요
WINHTTrack/wget으로는 :) 다행이 잘긁어지네요 어흐... 지금 나온 plugin중에
Static Snapshot 사용중에있습니다.

**Comment by Kn-Slyr** [comment]
제가 사용중인게 Static-html-output-plugin인데 index.html이 첫페이지 말씀하시는건가요? 음.. 전 잘 만들어진거같은데... 흠 뭐가 문제지...

**Comment by S-H-G** [comment]
@Kn-Slyr 지금 제가 이용하는 magicbook은 Shadow DOM을 통해 캡슐화서를 해서인지
Simply-static은 긁어지나 테마가 적용이 안되어있고
Static-html-output-plugin은 index.html이 안긁어지는 이슈가 있습니다:)
참고 : https://www.html5rocks.com/ko/tutorials/webcomponents/shadowdom-301/
