### ISSUE TITLE
팀 구성발표 위키

### ISSUE THREAD

**Issue by wskim3173** [SKKU-OSS-DO/SKKU-OSS-DO.github.io#9]
가장 최근에 발표했던 팀 구성발표를 위키로 작성하는게 좋을까요?
필요하다 생각하시면 코멘트 남겨주세요. 그럼 제가 진행하도록 하겠습니다.

**Comment by S-H-G** [comment]
혹시 팀 구성발표라 함은 어떤것을 이야기 하시는건가요?

**Comment by wskim3173** [comment]
활동소개, Github 활용, 정적 홈페이지, 커뮤니티 공헌, 일정 등 12주차에 발표했던 내용이요.

**Comment by wskim3173** [comment]
늦었지만 팀 구성발표 wiki 페이지 작성할게요. 빨리해야겠네요,
